[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Sean Daly", email = "the_sean_c@fastmail.com"},
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = {text = "GNU AGPLv3"}

